# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: net-attach-def-admission-controller
  name: net-attach-def-admission-controller-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-attach-def-admission-controller
  template:
    metadata:
      labels:
        app: net-attach-def-admission-controller
    spec:
      containers:
      - name: net-attach-def-admission-controller
        image: net-attach-def-admission-controller
        command:
        - webhook
        args:
        - -bind-address=0.0.0.0
        - -port=443
        - -tls-private-key-file=/webhook/tls/key.pem
        - -tls-cert-file=/webhook/tls/cert.pem
        - -alsologtostderr=true
        volumeMounts:
        - mountPath: /webhook/tls
          name: net-attach-def-admission-controller-secret
          readOnly: True
        imagePullPolicy: IfNotPresent
      volumes:
      - name: net-attach-def-admission-controller-secret
        secret:
          secretName: net-attach-def-admission-controller-secret
