language: go
go:
  - "1.11"
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.13.2 && go install && cd -
  - glide install --strip-vendor
script: make && make test
